openapi: 3.0.0
info:
  title: Service Reservas App
  description: Service Reservas App
  termsOfService: https://sample.com/terms/
  contact:
    name: API Support
    url: https://www.sample.com/support
    email: support@sample.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
  - url: http://localhost:5000/service--reservas-app
  - url: https://apps-dev.grupo.com.br/sample
  - url: http://localhost:9090/service--reservas-app
components:
  schemas:
    GeneralError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    ReservaError:
      type: object
      properties:
        code:
          type: string
          description: Error Code
        message:
          type: string
          description: Error Description
    SampleResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
    ReservaRequest:
      type: object
      properties:
        nomeCliente:
          type: string
        dataEntrada:
          type: string
        dataSaida:
          type: string
        numeroHospedes:
          type: string
    ReservaResponse:
      type: object
      properties:
        nomeCliente:
          type: string
        dataEntrada:
          type: string
        dataSaida:
          type: string
        numeroHospedes:
          type: string
    ClienteRequest:
      type: object
      properties:
        nomeCompleto:
          type: string
        telefone:
          type: string
        email:
          type: string
        cpf:
          type: string
        dataNascimento:
          type: string
        sexo:
          type: string
        endereco:
          $ref: '#/components/schemas/EnderecoRequest'
    ClienteResponse:
      type: object
      properties:
        nomeCompleto:
          type: string
        telefone:
          type: string
        email:
          type: string
        cpf:
          type: string
        dataNascimento:
          type: string
        sexo:
          type: string
        endereco:
          $ref: '#/components/schemas/EnderecoResponse'
    EnderecoRequest:
      type: object
      properties:
        rua:
          type: string
        cidade:
          type: string
        estado:
          type: string
        cep:
          type: string
        complemento:
          type:  string
    EnderecoResponse:
      type: object
      properties:
        rua:
          type: string
        cidade:
          type: string
        estado:
          type: string
        cep:
          type: string
        complemento:
          type: string
  responses:
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralError'
paths:
  /create-client:
    post:
      tags:
        - client
      summary: Add a new client
      description: Add a new client
      operationId: addClient
      requestBody:
        description: Create a new client
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/ClienteRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ClienteRequest'
        required: true
      responses:
        '200':
          description: Client created with sucess
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ClienteResponse'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /create-reserve:
    post:
      tags:
        - reserve
      summary: Add a new reserve
      description: Add a new reserve
      operationId: addReserve
      requestBody:
        description: Create a new reserve
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservaRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/ReservaRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ReserveRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservaResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ReservaResponse'
        '400':
          description: Invalid input
        '422':
          description: Validation exception


